server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-login
              uri: http://auth-service:8081
              predicates:
                Path=/api/v1/auth/login
              filters:
              - StripPrefix=2
              - name: RequestRateLimiter
                args:
                  redis-rate-limiter.replenishRate: 5
                  redis-rate-limiter.burstCapacity: 5
                  redis-rate-limiter.requestedTokens: 1
                  key-resolver: "#{@ipKeyResolver}"

            - id: auth-register
              uri: http://auth-service:8081
              predicates:
                Path=/api/v1/auth/register
              filters:
                - StripPrefix=2
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 3
                    redis-rate-limiter.burstCapacity: 3
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@ipKeyResolver}"

            - id: auth-service
              uri: http://auth-service:8081
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - StripPrefix=2

            - id: payment-service
              uri: http://payment-service:8082
              predicates:
                - Path=/api/v1/payments/**,/api/v1/accounts/**
              filters:
                - StripPrefix=2
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 10
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@ipKeyResolver}"

            - id: fraud-service
              uri: http://fraud-service:8083
              predicates:
                - Path=/api/v1/fraud/**
              filters:
                - StripPrefix=2

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:5173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true

jwt:
  secret: 2Qj3ZpP1QqWn5J6c6h1s7Q9sQ3k8Xb9mF4yJc0rP2tU=

api_prefix: "/api/v1"

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0  # 100% sampling for development
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs